# Migration script generated by Alembic
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '<revision_id>'
down_revision = '<previous_revision_id>'
branch_labels = None
depends_on = None

def upgrade():
op.add_column('developers', sa.Column('email', sa.String(length=255), nullable=False, unique=True))

def downgrade():
op.drop_column('developers', 'email')